id: jbossdemocentral-bpms-rewards
title: JBoss BPM Suite Rewards Demo
github_repo_url: https://github.com/jbossdemocentral/bpms-rewards-demo
technologies:
  - JBoss EAP
  - JBoss BPM Suite
summary: This is the HR employee rewards demo that provides examples of human task integration, form designer and a custom email work item handler. There are three options available to you for using this demo; local, OpenShift and containerized.
level: Beginner
product: bpmsuite
author: Andrew Block, Eric D. Schabell
